name: catch2 tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install clang-format
      run: brew install clang-format
    - name: Check all hpp file formatting
      run: clang-format --dry-run -Werror -style=file ./include/*.hpp
    - name: Check all cpp file formatting
      run: clang-format --dry-run -Werror -style=file ./src/*.cpp
    - name: Build Project and Tests
      run: make
    - name: Run Tests
      run: ./tests
