name: catch2 tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install clang-format
    - run: sudo apt-get install clang-format
    - name: Check all hpp file formatting
    - run: clang-format --dry-run -style=file ./include/*.hpp
    - name: Check all cpp file formatting
    - run: clang-format --dry-run -style=file ./src/*.cpp
    - name: Build Project and Tests
    - run: make
    - name: Run Tests
    - run: ./tests
